from qiskit import QuantumCircuit, transpile, ClassicalRegister
from qiskit.transpiler import PassManager
from CustomPass import CustomOptimizationPass
from NoiseModel import error_cost_function
from NativeGateMapping import NativeGateMap
from qiskit.circuit.random import random_circuit
import random
import numpy as np
import matplotlib.pyplot as plt

#Custom Pass Manager
pm = PassManager([CustomOptimizationPass()])
#Custom Native Gate Mapping
ngMap = NativeGateMap()

def example_qc():
    """Example QuantumCircuit that demonstrates all optmisation functionalities of the CustomOptimizationPass"""
    qc = QuantumCircuit(2)
    qc.x(0)
    qc.x(0)
    qc.cx(0,1)
    qc.cx(0,1)
    qc.barrier()
    qc.y(0)
    qc.y(0)
    qc.z(0)
    qc.cx(1,0)
    qc.rx(0.5,0)
    qc.rx(0.3,0)
    qc.crx(0.2,0,1)
    qc.crx(0.2,0,1)
    qc.ry(0.2,0)
    qc.ry(0.2,0)
    qc.rz(0.6,0)
    qc.crx(0.3,1,0)
    qc.ry(0.2,0)
    c = ClassicalRegister(1)
    qc.add_register(c)
    qc.measure(0,0)

    return qc

def print_circ_metrics(original_qc, optimised_qc, circuits = False):
    """
    Prints both the original and optimised circuits as generated by the CustomOptimizationPass along with their 
    circuit depths and total approximate error as defined by the custom noise model.
    """
    
    if circuits:
        print("Original circuit:")
        print(original_qc)

    if circuits:
        print("Optimized circuit:")
        print(optimised_qc)

    print("Circuit Depths:")
    print("Un-optimized: ",original_qc.depth())
    print("Optimized: ",optimised_qc.depth())

    print("\nErrors:")
    print("Un-optimized: ",error_cost_function(original_qc))
    print("Optimized: ",error_cost_function(optimised_qc))
    print("Error Ratio: ",round(100*error_cost_function(optimised_qc)/error_cost_function(original_qc),2),"%")

    return None

def custom_random_circuit(num_qubits:int,depth:int):
    """
    Generates a random circuit using the subset of gates X, Y, Z, RX, RY, RZ and their controlled versions.

    :param num_qubits: Number of qubits in the generated circuit.
    :type num_qubits: int
    :param depth: Depth of the generated circuit.
    :type depth: int
    :param max_operands: Maximum number of qubit operands in the generated circuit.
    :type max_operands: int
    :returns qc: The randomly generated quantum circuit.
    :rtype: QuantumCircuit
    """

    qc = QuantumCircuit(num_qubits)
    gate_set = ["x","y","z","rx","ry","rz","cx","cy","cz","crx","cry","crz"]

    for i in range(depth):
        for j in range(num_qubits):
            gate_name = gate_set[random.randint(0,len(gate_set)-1)]
            if "c" in gate_name and "r" not in gate_name:
                qubit = random.randint(0, num_qubits-1)
                #Prevents control gates being mapped to a single qubit
                while qubit == j:
                    qubit = random.randint(0, num_qubits-1)
                qc = apply_XYZ(circ = qc,gate_name = gate_name, qubits = [j,qubit])
            if "r" in gate_name and "c" not in gate_name:
                theta = random.uniform(0,2*np.pi)/(2*np.pi)
                qc = apply_XYZ(circ = qc,gate_name = gate_name, qubits = [j], theta = theta)
            if len(gate_name) == 3:
                theta = random.uniform(0,2*np.pi)/(2*np.pi)
                qubit = random.randint(0, num_qubits-1)
                #Prevents control gates being mapped to a single qubit
                while qubit == j:
                    qubit = random.randint(0, num_qubits-1)
                qc = apply_XYZ(circ = qc,gate_name = gate_name, qubits = [j,qubit], theta = theta)
            if len(gate_name) == 1:
                qc = apply_XYZ(circ = qc,gate_name = gate_name, qubits = [j])

    return qc

def apply_XYZ(circ: QuantumCircuit, gate_name:str, qubits:list, theta = None):
    """
    Helper function to apply the correct gate given a gate name string from the defined dubset of allowed gates in 
    :python:`custom_random_circuit`.
    """
    if "x" in gate_name:
        if len(qubits) == 2 and theta == None:
            circ.cx(qubits[0],qubits[1])
        elif len(qubits) == 2 and theta != None:
            circ.crx(theta,qubits[0],qubits[1])
        else:
            circ.x(qubits[0])
    if "y" in gate_name:
        if len(qubits) == 2 and theta == None:
            circ.cy(qubits[0],qubits[1])
        elif len(qubits) == 2 and theta != None:
            circ.cry(theta,qubits[0],qubits[1])
        else:
            circ.y(qubits[0])
    if "z" in gate_name:
        if len(qubits) == 2 and theta == None:
            circ.cz(qubits[0],qubits[1])
        elif len(qubits) == 2 and theta != None:
            circ.crz(theta,qubits[0],qubits[1])
        else:
            circ.z(qubits[0])
    
    return circ

def plot_errors(num_runs:int, num_qubits:int, depth:int, filename = "Random Circuit Optimized Error Ratios"):
    runs = [i for i in range(num_runs)]
    error_ratios = []
    for i in range(num_runs):
        qc = custom_random_circuit(num_qubits,depth)
        optimized_qc = pm.run(qc)
        error_ratios.append(error_cost_function(optimized_qc)/error_cost_function(qc))
    plt.clf()
    plt.plot(runs,error_ratios, color = 'r')
    plt.xlabel("Random Circuit Number")
    plt.ylabel("Ratio of Approximate Error: e_{opt}/e_{org}")
    plt.savefig(filename)

    return None

def true_random_circuit():
    qc = random_circuit(num_qubits=2, depth=10, max_operands=2)
    optimized_qc = pm.run(qc)

    count = 0
    while qc.depth() == optimized_qc.depth():
        qc = random_circuit(num_qubits=2, depth=10, max_operands=2)
        optimized_qc = pm.run(qc)
        count+=1

    print_circ_metrics(qc,optimized_qc)
    print("\nRandom Circuit No. ",count)

    return None

def random_native_gate_optimisation(num_qubits:int,depth:int,circuits = False):

    qc = custom_random_circuit(num_qubits,depth)
    if circuits:
        print(qc)
    mapped_qc = ngMap.map(qc)
    if circuits:
        print(mapped_qc)
    optimized_qc = pm.run(mapped_qc)
    if circuits:
        print(optimized_qc)
    
    print("Depths: \n Original Random Circuit: ",qc.depth(),"\n Native Gate Set Mapped Circuit: ",mapped_qc.depth(),"\n Optimized Circuit: ",optimized_qc.depth())

def plot_depths_ngMap(num_runs:int, num_qubits:int, depth:int, filename = "Random Circuit Optimized Error Ratios"):
    runs = [i for i in range(num_runs)]
    depth_ratios = []
    for i in range(num_runs):
        qc = custom_random_circuit(num_qubits,depth)
        mapped_qc = ngMap.map(qc)
        optimized_qc = pm.run(mapped_qc)
        depth_ratios.append(optimized_qc.depth()/mapped_qc.depth())
    plt.clf()
    plt.plot(runs,depth_ratios, color = 'r')
    plt.xlabel("Random Circuit Number")
    plt.ylabel("Ratio of Depth: d_{opt}/d_{map}")
    plt.savefig(filename)

    return None

#plot_depths_ngMap(100,2,10,"Q2D10R100NG")
#plot_errors(100,2,10,"Q2D10R100")